### PR TITLE
Feat(Menu and Team)

### PR DESCRIPTION
**Pull request by MuhammadAnas190**
- Created common style
- Header Menu sign out layout interface
- Added my Github link in Web Team JSON

### CODE REVIEW

**Comment by MuhammadAnas190** [comment]
Request Form for a Blog feature.
 - Blog form
 - Menu Icon bug fix

**Comment by SamiHK** [comment]
image

Anas it looks amazing, a minor bug please remove users' image after logout.

**Comment by MuhammadAnas190** [comment]
@SamiHK Please merge the bug fix.

**Comment by SamiHK** [comment]
@MuhammadAnas190 did you push changes? got no change on branch.

**Pull request merged**
